name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - anaconda
dependencies:
  - python={{ cookiecutter.python_interpreter }}
  - click
  - coverage
  - Cython
  - dvc
  - jupyterlab
  - pre_commit
  - sphinx
  - pip
  - pip:
      - optuna
      - python-dotenv>=0.5.1
